apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    # This selector directs traffic to either Blue or Green based on the label. 
    # Change 'blue' to 'green' to switch traffic instantly.
    app: backend
    version: blue
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000
  type: ClusterIP
